---
- name: "vault"
  unarchive:
    src: "{{ vault_url }}"
    dest: "{{ installation_path }}"
    creates: "{{ installation_path }}/vault"
    remote_src: true
    validate_certs: yes
  become: true

- name: "consul"
  unarchive:
    src: "{{ consul_url }}"
    dest: "{{ installation_path }}"
    creates: "{{ installation_path }}/consul"
    remote_src: true
    validate_certs: yes
  become: true
