---
- name: "vault : download"
  get_url:
    url:
    dest: "{{ ansible_user_dir }}/vault_0.7.3_linux_amd64.zip"

- name: "vault : unzip"
  unarchive:
    src: "{{ vault_url }}"
    dest: "{{ installation_path }}"
    creates: "{{ installation_path }}/vault"
    remote_src: true
    validate_certs: yes
  become: true

- name: "vault : cleanup archive"
  file:
    path: "{{ ansible_user_dir }}/vault_0.7.3_linux_amd64.zip"
    state: absent
