---
- name: "download visual studio {{ vs.version }} iso"
  win_get_url:
    url: "{{ vs.iso.url }}"
    dest: "{{ ansible_user_dir }}\\{{ vs.iso.filename }}"
    force: no

- name: "extract files from visual studio {{ vs.version }} iso"
  win_command: 7z x -aos -o"{{ vs.installer.path }}" "{{ ansible_user_dir }}\\{{ vs.iso.filename }}"

# alternative ways of extracting files from iso image
# windows 2012+
# - name: "mount visual studio image"
#   win_disk_image:
#     image_path: "{{ ansible_user_dir }}/{{ visualstudio.iso.filename }}"
#     state: present
#   register: visualstudio.iso.mountpoint

# not working with udf iso images
# - name: "extract files from visual studio {{ vs.version }} iso"
#   win_unzip:
#     src: "{{ ansible_user_dir }}\\{{ vs.iso.filename }}"
#     dest: "{{ vs.installer.path }}"
#    creates: "{{ vs.installer.path }}\\vs\\Setup\\setup.exe"

- name: "copy unattended installation script"
  win_copy:
    src: "{{ vs.installer.ini }}"
    dest: "{{ ansible_user_dir }}\\{{ vs.installer.ini }}"

- name: "start unattended installation"
  win_command: "{{ vs.installer.path }}\\setup\\setup.exe /unattendfile {{ ansible_user_dir }}\\{{ vs.installer.ini }}"
