---
- name: "install Visual Studio 2005"
  include: visualstudio-2005.yml
  tags:
    - vs2005
    - vs

- name: "install Visual Studio 2008"
  include: visualstudio-2008.yml
  tags:
    - vs2008
    - vs

- name: "install python, pywin and scons"
  include: python.yml
  tags:
    - python
    - pywin
    - scons

- name: "install perl and perl modules"
  include: perl.yml
  tags:
    - perl
