---
- name: "install Visual Studio 2005"
  include: visualstudio-2005.yml
  tags:
    - vs
    - vs2005

- name: "install Visual Studio 2008"
  include: visualstudio-2008.yml
  tags:
    - vs
    - vs2008

- name: "install Visual Studio 2012"
  include: visualstudio-2012.yml
  tags:
    - vs
    - vs2012

- name: "install python, pywin and scons"
  include: python.yml
  tags:
    - python
    - pywin
    - scons

- name: "install perl and perl modules"
  include: perl.yml
  tags:
    - perl

- name: "reboot"
  win_reboot:
