# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  config.vm.hostname = "desktop.ecosystem"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "desktop"
    vb.cpus = 2
    vb.memory = 4096
  end

  config.vm.network "forwarded_port", guest: 22, host: 4422
  config.vm.network "forwarded_port", guest: 3389, host: 4489

  config.vm.provision "shell", path: "provision.sh"
end
