---
- name: "create xfce4 config directory"
  file:
    path: "{{ ansible_user_dir }}/.config/xfce4"
    state: directory

- name: "apply xfce4 default panel settings"
  shell: "cp -r /etc/xdg/xfce4/panel {{ ansible_user_dir }}/.config/xfce4"

- name: "apply xfce4 default configuration settings"
  shell: "cp -r /etc/xdg/xfce4/xfconf {{ ansible_user_dir }}/.config/xfce4"

- name: "disable tab window switching"
  shell: "sed -i 's|switch_window_key|empty|g' {{ ansible_user_dir }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: "change screen lock shortcut"
  shell: "sed -i 's|&lt;Primary&gt;&lt;Alt&gt;Delete|&lt;Super&gt;l|g' {{ ansible_user_dir }}/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-keyboard-shortcuts.xml"

- name: "set file ownership"
  file:
    path: "{{ ansible_user_dir }}/.config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    recurse: yes
