---
- name: "Install xfc4 desktop"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
      - xfce4
      - xfce4-goodies
  become: true

- name: "Install xrdp"
  apt:
    name: xrdp
    state: present
  become: yes
