---
- name: "Install xfce4 desktop"
  yum:
    name: xfdesktop
    state: present
    update_cache: yes
  become: true

- name: "Install xrdp"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - xrdp
    - tigervnc-server
  become: true

- name: "Make sure xrdp service is running"
  systemd:
    name: xrdp
    state: started
  become: true

# - name: "Enable xrdp in firewall"
#   firewalld:
#     port: 3389/tcp
#     permanent: true
#     state: enabled
#     zone: public
#   become: true
