---
- name: "install xubuntu"
  apt:
    name: xubuntu-core
    state: present
    update_cache: yes
  become: true

- name: "install virtualbox guest additions"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - virtualbox-guest-utils
    - virtualbox-guest-dkms
    - virtualbox-guest-x11
  become: true

# - name: "download virtualbox guest additions iso"
#   get_url:
#     url: "{{ virtualbox_url }}/{{ virtualbox.version }}/VBoxGuestAdditions_{{ virtualbox.version }}.iso"
#     dest: "{{ ansible_user_dir }}"
#     force: no
#
# - name: "create iso mountpoint"
#   file:
#     path: "/mnt/iso"
#     state: directory
#   become: true
#
# - name: "mount virtualbox guest additions iso"
#   mount:
#     path: "/mnt/iso"
#     src: "{{ ansible_user_dir }}/VBoxGuestAdditions_{{ virtualbox.version }}.iso"
#     fstype: iso9660
#     opts: ro
#     state: mounted
#   become: true
