---
- name: "download Chocolatey installation script"
  win_get_url:
    url: https://chocolatey.org/install.ps1
    dest: "{{ ansible_user_dir }}/install-choco.ps1"

- name: "run Chocolatey installtion script"
  win_shell: "powershell -NoProfile -ExecutionPolicy Bypass \"& \"\"C:\\users\\administrator\\install-choco.ps1\"\"\""

- name: "ensure that Chocolatey is in PATH"
  win_path:
    elements:
    - '%ALLUSERSPROFILE%\\chocolatey\\bin\\'

- name: "remove Chocolatey installtion script"
  win_file:
    path: "{{ ansible_user_dir }}/install-choco.ps1"
    state: absent
