---
- name: "create base directory"
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ owner }}"
    group: "{{ group }}"
  become: true

- name: "check if already installed"
  stat:
    path: "{{ java_dir }}/bin/java"
  register: java_binary

- name: "download archive"
  get_url:
    url: "{{ java_url_prefix }}{{ java_version }}/{{ java_url_hash }}/{{ java_tgz }}"
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: "{{ base_dir }}/{{ java_tgz }}"
    force: no
  retries: 5
  when: java_binary.stat.exists == false
  become: true

- name: "extract archive"
  unarchive:
    src: "{{ base_dir }}/{{ java_tgz }}"
    remote_src: yes
    dest: "{{ base_dir }}"
    creates: "{{ java_dir }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
  when: java_binary.stat.exists == false
  become: true

- name: "create link to current version directory"
  file:
    path: "{{ java_home }}"
    src: "{{ java_dir }}"
    state: link
  become: true

- name: "create /usr/bin links"
  file:
    path: "/usr/bin/{{ item }}"
    src: "{{ java_home }}/bin/{{ item }}"
    state: link
  with_items:
    - java
    - javac
    - javadoc
    - javafxpackager
    - javah
    - javap
    - javapackager
    - javaws
  become: true

- name: "set environmental variables"
  template:
    src: java.sh.j2
    dest: "/etc/profile.d/java.sh"
  become: true

- name: "remove archive"
  file:
    path: "{{ base_dir }}/{{ java_tgz }}"
    state: absent
  become: true
