---
- name: "add java repository"
  apt_repository:
    repo: "ppa:webupd8team/java"
    state: present
    update_cache: yes
  become: true

- name: "accept Java 8 License"
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: "install java"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - ca-certificates
  become: true

- name: "install maven"
  apt:
    name: maven
    state: present
  become: true
