# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
nodes = YAML.load_file('vagrant-inventory.yml')

Vagrant.configure(2) do |config|
  nodes.each do |nodes|
    config.vm.define nodes["name"] do |node|
      # vm settings
      node.vm.box = nodes["box"]
      node.vm.hostname = nodes["name"]
      node.vm.box_check_update = nodes["check_updates"]
      node.vm.network nodes["net"], ip: nodes["ip"]

      # settings for windows
      if nodes["box"].include? "windows"
        node.vm.guest = :windows
        node.vm.communicator = "winrm"
      end

      # virtualbox settings
      node.vm.provider "virtualbox" do |vb|
          vb.name = nodes["name"]
          vb.memory = nodes["mem"]
          vb.cpus = nodes["cpus"]

          # gui settings
          if nodes["gui"]
            vb.gui = nodes["gui"]
            vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
          end
      end

      # ports
      if nodes["ports"]
        nodes["ports"].each do |port|
          node.vm.network "forwarded_port", guest: port["guest"], host: port["host"], id: port["id"]
        end
      end

      # synced folders
      node.vm.synced_folder "../ansible/", "/ansible"

      # provisioning
      node.vm.provision "file", source: ".bashrc", destination: ".bashrc"
      if nodes["script"]
          node.vm.provision "shell", path: nodes["script"], privileged: false
      end
      if nodes["ansible"]
        node.vm.provision "ansible_local" do |ansible|
          ansible.playbook = nodes["ansible"]
          ansible.provisioning_path = "/ansible"
        end
      end

    end
  end
end
