---
- name: "install useful ubuntu specific packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unattended-upgrades
    - ssh
  become: true
  tags:
    - packages
