---
- name: "install useful packages"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - openssh
    - openssh-clients
    - openssh-server
    - redhat-lsb-core
    - net-tools
    - epel-release
    - kernel-headers
    - kernel-devel
  become: true

- name: "Disable selinux"
  selinux:
    state: disabled
  become: true
