---
- name: "install useful packages"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - unattended-upgrades
    - ssh
    - tmux
    - ncdu
    - htop
  become: true
