---
- name: "install common packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - git
    - zip
    - unzip
    - tar
    - wget
    - htop
    - tmux
    - ncdu
    - htop
  become: true

- include: common-apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: common-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: "provide .vimrc"
  copy:
    src: ".vimrc"
    dest: "{{ ansible_user_dir }}"

- name: "update /etc/hosts file"
  blockinfile:
    block: "{{ lookup('file', 'templates/hosts') }}"
    dest: "/etc/hosts"
    backup: yes
  become: true
