---
- name: "install common packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - git
  become: true

- include: common-apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: common-yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: "provide .vimrc"
  copy:
    src: ".vimrc"
    dest: "{{ ansible_user_dir }}"
