---
- include: common-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include: common-centos.yml
  when: ansible_distribution == 'CentOS'

- name: "install common packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - git
    - zip
    - unzip
    - tar
    - wget
    - ca-certificates
    - htop
    - tmux
    - ncdu
  become: true
  tags:
    - packages

- name: "user setup"
  user:
    name: "{{ ansible_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    password: '$6$ci45Bc.7Fc181jeL$ub7930PGzGPp2kqUZ8c8gMonI/0j9xfrEqsNxqZ./z8E9GnEcTqn1tc63gas.w9zHgdtB.fDRglqHF1KpZB87/'
  become: true
  tags:
    - password
    - user

- name: "provide .bashrc"
  copy:
    src: ".bashrc"
    dest: "{{ ansible_user_dir }}"
    mode: 0660
  tags:
    - user

- name: "provide .vimrc"
  copy:
    src: ".vimrc"
    dest: "{{ ansible_user_dir }}"
    mode: 0660
  tags:
    - user

- name: "make sure .ssh directory exists"
  file:
    path: "{{ ansible_user_dir}}/.ssh"
    state: directory
  tags:
    - user
    - ssh

- name: "provide ssh config"
  blockinfile:
    block: "{{ lookup('file', 'ssh.config') }}"
    dest: "{{ ansible_user_dir}}/.ssh/config"
    backup: yes
    create: yes
  become: true
  tags:
    - user
    - ssh

- name: "update /etc/hosts file"
  blockinfile:
    block: "{{ lookup('file', 'hosts') }}"
    dest: "/etc/hosts"
    backup: yes
  become: true
  tags:
    - hosts

- name: "set timezone"
  timezone:
    name: "CET"
  become: true
  tags:
    - time
