---
- name: "Install useful packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - vim
    - git
    - python-pip
  become: true

- include: debian.yml
  when:
    - ansible_os_family == "Debian"

- include: redhat.yml
  when:
    - ansible_os_family == "RedHat"
