---
- name: "create base directory"
  file:
    path: "{{ groovy_base }}"
    state: directory
    owner: "{{ groovy_owner }}"
    group: "{{ groovy_group }}"
  become: true

- name: "check if already installed"
  stat:
    path: "{{ groovy_dir }}/bin/groovy"
  register: groovy_binary

- name: "download and unzip"
  unarchive:
    src: "{{ groovy_url }}"
    creates: "{{ groovy_dir }}"
    dest: "{{ groovy_base }}"
    validate_certs: yes
    remote_src: yes
  when: groovy_binary.stat.exists == false
  become: true

- name: "create link to current version"
  file:
    path: "{{ groovy_home }}"
    src: "{{ groovy_dir }}"
    state: link
    owner: "{{ groovy_owner }}"
    group: "{{ groovy_group }}"
  become: true

- name: "create /usr/bin/groovy link"
  file:
    path: "/usr/bin/groovy"
    src: "{{ groovy_home }}/bin/groovy"
    state: link
  become: true

- name: "set environmental variables"
  template:
    src: groovy.sh.j2
    dest: "/etc/profile.d/groovy.sh"
  become: true
