# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |node|
  node.vm.box = "ubuntu/xenial64"
  node.vm.hostname = "controller.ecosystem"

  node.vm.network "private_network", ip: "10.0.0.10"

  node.vm.provision :shell, path: "provision.sh"
  node.vm.provision "file", source: ".bashrc", destination: ".bashrc"

  node.vm.synced_folder "../../ansible/", "/ansible"

  node.vm.provider "virtualbox" do |vb|
    vb.name = "controller"
    vb.cpus = 1
    vb.memory = "256"
  end
end
