---
- name: "install git"
  win_chocolatey:
    name: git
    state: present

- name: "install Notepad++"
  win_chocolatey:
    name: notepadplusplus
    state: present

- name: "install 7zip"
  win_chocolatey:
    name: 7zip
    state: present

- name: "install Python 2.X"
  win_chocolatey:
    name: python2
    state: present
