swarm_client_version: "3.4"
swarm_client_jar: "swarm-client-{{ swarm_client_version }}.jar"
swarm_client_url: "https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ swarm_client_version}}/{{ swarm_client_jar }}"

master: "http://jenkins-master"
user: "jenkins"
password: "jenkins"

labels: 'java'
executors: 1
