Vagrant.configure("2") do |config|
  config.vm.box = "windows/2012r2"
  config.vm.hostname = "windows-2012"
  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  # virtualbox settings
  config.vm.provider "virtualbox" do |vb|
      vb.name = "windows-2012"
      vb.memory = 4096
      vb.cpus = 1
      vb.gui = true

      # enable clipboard sharing
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end
end
