---
# get certificate from http://uk1vswcert01/certsrv/certcarc.asp
- name: "copy certificate"
  copy:
    src: misys.cer
    dest: "{{ ansible_user_dir }}/misys.cer"

- name: "install certificate"
  become: yes
  become_method: sudo
  shell: "openssl x509 -inform DER -outform PEM -in {{ ansible_user_dir }}/misys.cer -out /usr/local/share/ca-certificates/misys.crt"

- name: "install certificate"
  become: yes
  become_method: sudo
  shell: "update-ca-certificates"

- name: "cleanup"
  file:
    path: "{{ ansible_user_dir }}/misys.cer"
    state: absent

- name: "create directory for Misys DTR certificates"
  become: yes
  become_method: sudo
  file:
    path: "/etc/docker/certs.d/{{ docker_registry }}/"
    recurse: yes
    state: directory

- name: "configure Misys DTR certificate"
  become: yes
  become_method: sudo
  shell: "openssl s_client -showcerts -connect {{ docker_registry }}:443 </dev/null 2>/dev/null |openssl x509 -outform PEM | tee /etc/docker/certs.d/{{ docker_registry }}/ca.crt"
