---
- name: "install"
  pip:
    name: robotframework
    state: present
  become: true

- name: "install useful libraries"
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - robotframework-sshlibrary
    - robotframework-selenium2library
    - robotframework-archivelibrary
  become: true
