---
- name: "install Python 2"
  apt:
    name: python
    state: present
    update_cache: yes
  become: true

- name: "install Python 3"
  apt:
    name: python3
    state: present
  become: true

- name: "install pip"
  apt:
    name: python-pip
    state: present
  become: true
