---
- name: "install Python 2"
  yum:
    name: "python2"
    state: present
    update_cache: yes
  become: true

- name: "install Python 3"
  yum:
    name: "python34"
    state: present
  become: true

- name: "install pip"
  yum:
    name: "python2-pip"
    state: present
  become: true
