---
- name: "create docker group"
  group:
    name: docker
    state: present
  become: true

- name: "add user to docker group"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: "download docker-compose"
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
  become: true

- name: "restart service"
  service:
    name: docker
    state: restarted
  become: true
