---
- name: "install prerequisits for apt"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
  become: true

- name: "add repository keys"
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  become: true

- name: "add repository"
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
    state: present
    update_cache: yes
  become: true

- name: "install recommended packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - linux-image-extra-virtual
    - linux-image-extra-{{ ansible_kernel }}
  become: true

- name: "install docker"
  apt:
    name: docker-engine
    state: present
    update_cache: yes
  become: true

- name: "create docker group"
  group:
    name: docker
    state: present
  become: true

- name: "add user to docker group"
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: "install docker-compose"
  pip:
    name: docker-compose
    state: present
