#!/bin/bash -e

# Script for applying ansible role to single host

function display_help {
  echo "$(basename $0) - script for applying ansible role to single host"
  echo "Usage:"
  echo "  $(basename $0) ROLE HOST"
}

if [[ $1 == "-h" || $1 == "--help" ]]; then
  display_help
  exit 0
fi

if [[ $# -lt 2 ]]; then
  display_help
  exit 1
fi

# variables
ROLE=$1
HOST=$2
PLAYBOOK="playbook-${ROLE}-${HOST}.yml"

# check input
if [[ ! -d "roles/${ROLE}" ]]; then
  echo "Role ${ROLE} doesn't exists"
  echo "Aborting"
  exit 1
fi

if [[ $(grep "${HOST}" inventory | wc -l) == 0 ]]; then
  echo "Host ${HOST} not found in the inventory"
  echo "Aborting"
  exit 1
fi

rm -rf "${PLAYBOOK}"

cat <<EOT >> ${PLAYBOOK}
---
- hosts: ${HOST}
  roles:
    - ${ROLE}
EOT

# remove ROLE and HOST from parameter list
shift 2

ansible-playbook "${PLAYBOOK}" "$@"
rm -rf "${PLAYBOOK}"
