---
- hosts: jenkins-master
  tasks:
    - name: "create jenkins folder"
      file:
        path: "{{ ansible_user_dir}}/jenkins"
        state: directory
# TODO parametrize version
    - name: "pull docker container"
      docker_image:
        name: jenkins:2.60.2

    - name: "start jenkins container"
      docker_container:
        name: jenkins
        image: jenkins:2.60.2
        state: started
        ports:
          - "80:8080"
          - "50000:50000"
        volumes:
          - "{{ ansible_user_dir}}/jenkins:/var/jenkins_home"
          - "/etc/ssl/certs:/etc/ssl/certs"

    - name: "create cron entry"
      cron:
        name: "start jenkins master"
        special_time: reboot
        job: "docker start jenkins"
