---
- name: "remove previous version"
  apt:
    name: "virtualbox"
    state: absent
  become: true

- name: "add repository keys"
  apt_key:
    url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
    state: present
  become: true

- name: "add repository"
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
    state: present
    update_cache: yes
  become: true

- name: "install"
  apt:
    name: "virtualbox-5.1"
    state: present
  become: true
