---
java:
  major: "8"
  minor: "144"
  build: "01"

jdk_url_prefix: "http://download.oracle.com/otn-pub/java/jdk/"
jdk_url_hash: "090f390dda5b47b9b721c7dfaa008135"
jdk_version: "{{ java.major }}u{{ java.minor }}-b{{ java.build }}"
jdk_rpm: "jdk-{{ java.major }}u{{ java.minor }}-linux-x64.rpm"
