---
vault_url: "https://releases.hashicorp.com/vault/0.7.3/vault_0.7.3_linux_amd64.zip"
consul_url: "https://releases.hashicorp.com/consul/0.9.3/consul_0.9.3_linux_amd64.zip"
installation_path: "/usr/local/bin"
